[profile.default]
src = "contracts"
out = "out"
libs = ["node_modules", "lib"]
remappings = [
    "@openzeppelin/=node_modules/@openzeppelin/",
    "erc721a/=node_modules/erc721a/",
    "operator-filter-registry/=node_modules/operator-filter-registry/",
    "solmate/=node_modules/solmate/",
]

# See more config options https://github.com/foundry-rs/foundry/tree/master/config